/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPack;

import java.awt.event.KeyEvent;

/**
 *
 * @author oSikaNi iSraeL
 */
public class Calculator_ extends javax.swing.JFrame {
    
    Double f_num;
    Double s_num;
    Double result;
    
    String operations;

    /**
     * Creates new form Calculator_
     */
    public Calculator_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnplus_minus = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn_mult = new javax.swing.JButton();
        btn_minus = new javax.swing.JButton();
        btnequalt = new javax.swing.JButton();
        btn_plus = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        lable = new javax.swing.JLabel();
        displayBox = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        dis = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn7.setBackground(new java.awt.Color(0, 0, 204));
        btn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 60, 60));

        btn4.setBackground(new java.awt.Color(0, 0, 204));
        btn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 60, 60));

        btnplus_minus.setBackground(new java.awt.Color(0, 0, 204));
        btnplus_minus.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnplus_minus.setForeground(new java.awt.Color(255, 255, 255));
        btnplus_minus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Plus Minus_32px.png"))); // NOI18N
        btnplus_minus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnplus_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplus_minusActionPerformed(evt);
            }
        });
        jPanel2.add(btnplus_minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 60, 60));

        btn0.setBackground(new java.awt.Color(0, 0, 204));
        btn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        btn0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn0KeyPressed(evt);
            }
        });
        jPanel2.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 60, 60));

        btn2.setBackground(new java.awt.Color(0, 0, 204));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 60, 60));

        btn5.setBackground(new java.awt.Color(0, 0, 204));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 60, 60));

        btn8.setBackground(new java.awt.Color(0, 0, 204));
        btn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 60, 60));

        btn_mult.setBackground(new java.awt.Color(0, 0, 204));
        btn_mult.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_mult.setForeground(new java.awt.Color(255, 255, 255));
        btn_mult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Multiply_32px.png"))); // NOI18N
        btn_mult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mult, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 60, 60));

        btn_minus.setBackground(new java.awt.Color(0, 0, 204));
        btn_minus.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_minus.setForeground(new java.awt.Color(255, 255, 255));
        btn_minus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Minus Math _32px.png"))); // NOI18N
        btn_minus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minusActionPerformed(evt);
            }
        });
        jPanel2.add(btn_minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 60, 60));

        btnequalt.setBackground(new java.awt.Color(0, 0, 204));
        btnequalt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnequalt.setForeground(new java.awt.Color(255, 255, 255));
        btnequalt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Equal Sign_32px.png"))); // NOI18N
        btnequalt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnequalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequaltActionPerformed(evt);
            }
        });
        jPanel2.add(btnequalt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 60, 60));

        btn_plus.setBackground(new java.awt.Color(0, 0, 204));
        btn_plus.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_plus.setForeground(new java.awt.Color(255, 255, 255));
        btn_plus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Plus Math_32px.png"))); // NOI18N
        btn_plus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plusActionPerformed(evt);
            }
        });
        jPanel2.add(btn_plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 60, 60));

        btndot.setBackground(new java.awt.Color(0, 0, 204));
        btndot.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btndot.setForeground(new java.awt.Color(255, 255, 255));
        btndot.setText(".");
        btndot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndot.setIconTextGap(50);
        btndot.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btndot.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });
        jPanel2.add(btndot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 60, 60));

        btn3.setBackground(new java.awt.Color(0, 0, 204));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 60, 60));

        btn6.setBackground(new java.awt.Color(0, 0, 204));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 60, 60));

        btn9.setBackground(new java.awt.Color(0, 0, 204));
        btn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 60, 60));

        jButton18.setBackground(new java.awt.Color(0, 0, 204));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Square Root_32px_1.png"))); // NOI18N
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 60, 60));

        btn_clear.setBackground(new java.awt.Color(0, 0, 204));
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("c");
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 60, 60));

        btn_del.setBackground(new java.awt.Color(0, 0, 204));
        btn_del.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_del.setForeground(new java.awt.Color(255, 255, 255));
        btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Clear Symbol_32px.png"))); // NOI18N
        btn_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });
        jPanel2.add(btn_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 60, 60));

        btn_div.setBackground(new java.awt.Color(0, 0, 204));
        btn_div.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_div.setForeground(new java.awt.Color(255, 255, 255));
        btn_div.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Divide_32px.png"))); // NOI18N
        btn_div.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });
        jPanel2.add(btn_div, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 60, 60));

        btn1.setBackground(new java.awt.Color(0, 0, 204));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 60, 60));

        lable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lable.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 40));

        displayBox.setBackground(new java.awt.Color(0, 0, 204));
        displayBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        displayBox.setForeground(new java.awt.Color(255, 255, 255));
        displayBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayBox.setBorder(null);
        displayBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                displayBoxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                displayBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                displayBoxKeyTyped(evt);
            }
        });
        jPanel2.add(displayBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 270, 50));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 270, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 130, 540, 520));

        dis.setEditable(false);
        dis.setBackground(new java.awt.Color(0, 0, 204));
        dis.setForeground(new java.awt.Color(255, 255, 255));
        dis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        dis.setBorder(null);
        jPanel2.add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 270, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 330, 550));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 360, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logoNew.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 80));

        jButton1.setBackground(new java.awt.Color(175, 165, 165));
        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back_25px_6.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 90, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("C A L C U L A T O R");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 70)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("STANDARD ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calculator.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        setSize(new java.awt.Dimension(709, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        String num4 = displayBox.getText()+btn4.getText(); 
        displayBox.setText(num4);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnplus_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplus_minusActionPerformed
        // TODO add your handling code here:
        int  ops = Integer.parseInt(String.valueOf(displayBox.getText()));
        
        ops = ops*(-1);
       
        displayBox.setText(String.valueOf(ops)); 
    }//GEN-LAST:event_btnplus_minusActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
          String num0 = displayBox.getText()+btn0.getText(); 
        displayBox.setText(num0);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
          String num2= displayBox.getText()+btn2.getText(); 
        displayBox.setText(num2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
         String num5 = displayBox.getText()+btn5.getText(); 
        displayBox.setText(num5);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minusActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_minusActionPerformed

    private void btnequaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequaltActionPerformed
        // TODO add your handling code here:

       
    }//GEN-LAST:event_btnequaltActionPerformed

    private void btn_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plusActionPerformed
        // TODO add your handling code here:
        
      
        
          
         
    }//GEN-LAST:event_btn_plusActionPerformed

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotActionPerformed
        // TODO add your handling code here:
          String numdot = displayBox.getText()+btndot.getText(); 
        displayBox.setText(numdot); 
    }//GEN-LAST:event_btndotActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
         String num3 = displayBox.getText()+btn3.getText(); 
        displayBox.setText(num3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        String num6 = displayBox.getText()+btn6.getText(); 
        displayBox.setText(num6);
    }//GEN-LAST:event_btn6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        main_form1 mf = new main_form1();
        mf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
         String num1 = displayBox.getText()+btn1.getText(); 
        displayBox.setText(num1);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn0KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn0KeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_0){
          String num0 = displayBox.getText()+btn0.getText(); 
        displayBox.setText(num0);
        }
    }//GEN-LAST:event_btn0KeyPressed

    private void displayBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayBoxKeyPressed
        // TODO add your handling code here:
        
       
        
       
    
          
        
    }//GEN-LAST:event_displayBoxKeyPressed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
         String num9 = displayBox.getText()+btn9.getText(); 
        displayBox.setText(num9);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
         String num8 = displayBox.getText()+btn8.getText(); 
        displayBox.setText(num8);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
         String num7 = displayBox.getText()+btn7.getText(); 
        displayBox.setText(num7);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
                displayBox.setText(null);
        lable.setText(null);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
        
        String bsp=null;
        
       if(displayBox.getText().length()>0){
       StringBuilder strB = new StringBuilder(displayBox.getText());
       strB.deleteCharAt(displayBox.getText().length()-1);
       bsp=strB.toString();
       displayBox.setText(bsp);
       }
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btn_divActionPerformed

    private void btn_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_multActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jButton18ActionPerformed

    private void displayBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayBoxKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isAlphabetic(c))
        {
            getToolkit().beep();
            evt.consume();
        }


 
    }//GEN-LAST:event_displayBoxKeyTyped

    private void displayBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayBoxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_displayBoxKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_minus;
    private javax.swing.JButton btn_mult;
    private javax.swing.JButton btn_plus;
    private javax.swing.JButton btndot;
    private javax.swing.JButton btnequalt;
    private javax.swing.JButton btnplus_minus;
    private javax.swing.JTextField dis;
    private javax.swing.JTextField displayBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lable;
    // End of variables declaration//GEN-END:variables
}
