/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPack;

/**
 *
 * @author oSikaNi iSraeL
 */
import java.math.*;
public class scientific_calculator extends javax.swing.JFrame {
 private boolean zerodisp;
  private boolean dcidisp;
  
  private byte op;
  private double ina;
  private double inb;
   private double out;
   private boolean degree;
   private boolean radiant;
   
    public scientific_calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnplus_minus = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn_mult = new javax.swing.JButton();
        btn_minus = new javax.swing.JButton();
        btnequalt = new javax.swing.JButton();
        btn_plus = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        displayBox = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        dis = new javax.swing.JTextField();
        memory_save = new javax.swing.JButton();
        memory_read = new javax.swing.JButton();
        memory_Clear = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        mem_dis = new javax.swing.JTextField();
        cos = new javax.swing.JButton();
        tan_1 = new javax.swing.JButton();
        sin_1 = new javax.swing.JButton();
        cos_1 = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        cube = new javax.swing.JButton();
        squared = new javax.swing.JButton();
        btn_clear12 = new javax.swing.JButton();
        btn_clear13 = new javax.swing.JButton();
        pi = new javax.swing.JButton();
        btn_clear15 = new javax.swing.JButton();
        oct = new javax.swing.JButton();
        hex = new javax.swing.JButton();
        exp = new javax.swing.JButton();
        cube_root = new javax.swing.JButton();
        log = new javax.swing.JButton();
        sq_root = new javax.swing.JButton();
        bin = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        combo = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn7.setBackground(new java.awt.Color(0, 0, 204));
        btn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 50, 30));

        btn4.setBackground(new java.awt.Color(0, 0, 204));
        btn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 50, 30));

        btnplus_minus.setBackground(new java.awt.Color(0, 0, 204));
        btnplus_minus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnplus_minus.setForeground(new java.awt.Color(255, 255, 255));
        btnplus_minus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Plus Minus_32px.png"))); // NOI18N
        btnplus_minus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnplus_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplus_minusActionPerformed(evt);
            }
        });
        jPanel2.add(btnplus_minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 50, 30));

        btn0.setBackground(new java.awt.Color(0, 0, 204));
        btn0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        btn0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn0KeyPressed(evt);
            }
        });
        jPanel2.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 50, 30));

        btn2.setBackground(new java.awt.Color(0, 0, 204));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 50, 30));

        btn5.setBackground(new java.awt.Color(0, 0, 204));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 50, 30));

        btn8.setBackground(new java.awt.Color(0, 0, 204));
        btn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 50, 30));

        btn_mult.setBackground(new java.awt.Color(0, 0, 204));
        btn_mult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_mult.setForeground(new java.awt.Color(255, 255, 255));
        btn_mult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Multiply_32px.png"))); // NOI18N
        btn_mult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mult, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 50, 30));

        btn_minus.setBackground(new java.awt.Color(0, 0, 204));
        btn_minus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_minus.setForeground(new java.awt.Color(255, 255, 255));
        btn_minus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Minus Math _32px.png"))); // NOI18N
        btn_minus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minusActionPerformed(evt);
            }
        });
        jPanel2.add(btn_minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 50, 30));

        btnequalt.setBackground(new java.awt.Color(0, 0, 204));
        btnequalt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnequalt.setForeground(new java.awt.Color(255, 255, 255));
        btnequalt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Equal Sign_32px.png"))); // NOI18N
        btnequalt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnequalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequaltActionPerformed(evt);
            }
        });
        jPanel2.add(btnequalt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 50, 30));

        btn_plus.setBackground(new java.awt.Color(0, 0, 204));
        btn_plus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_plus.setForeground(new java.awt.Color(255, 255, 255));
        btn_plus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Plus Math_32px.png"))); // NOI18N
        btn_plus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plusActionPerformed(evt);
            }
        });
        jPanel2.add(btn_plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 50, 30));

        btndot.setBackground(new java.awt.Color(0, 0, 204));
        btndot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndot.setForeground(new java.awt.Color(255, 255, 255));
        btndot.setText(".");
        btndot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndot.setIconTextGap(50);
        btndot.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btndot.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });
        jPanel2.add(btndot, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 50, 30));

        btn3.setBackground(new java.awt.Color(0, 0, 204));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 50, 30));

        btn6.setBackground(new java.awt.Color(0, 0, 204));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 50, 30));

        btn9.setBackground(new java.awt.Color(0, 0, 204));
        btn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 50, 30));

        reset.setBackground(new java.awt.Color(0, 0, 204));
        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("ce");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 50, 30));

        btn_clear.setBackground(new java.awt.Color(0, 0, 204));
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("c");
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 50, 30));

        btn_del.setBackground(new java.awt.Color(0, 0, 204));
        btn_del.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_del.setForeground(new java.awt.Color(255, 255, 255));
        btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Clear Symbol_32px.png"))); // NOI18N
        btn_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });
        jPanel2.add(btn_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 50, 30));

        btn_div.setBackground(new java.awt.Color(0, 0, 204));
        btn_div.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_div.setForeground(new java.awt.Color(255, 255, 255));
        btn_div.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Divide_32px.png"))); // NOI18N
        btn_div.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });
        jPanel2.add(btn_div, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 50, 30));

        btn1.setBackground(new java.awt.Color(0, 0, 204));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 50, 30));

        displayBox.setBackground(new java.awt.Color(0, 0, 204));
        displayBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        displayBox.setForeground(new java.awt.Color(255, 255, 255));
        displayBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayBox.setText("0");
        displayBox.setBorder(null);
        displayBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBoxActionPerformed(evt);
            }
        });
        displayBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                displayBoxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                displayBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                displayBoxKeyTyped(evt);
            }
        });
        jPanel2.add(displayBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 420, 50));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 420, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 190, 130));

        dis.setEditable(false);
        dis.setBackground(new java.awt.Color(0, 0, 204));
        dis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dis.setForeground(new java.awt.Color(255, 255, 255));
        dis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        dis.setBorder(null);
        jPanel2.add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 420, 50));

        memory_save.setBackground(new java.awt.Color(0, 0, 204));
        memory_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        memory_save.setForeground(new java.awt.Color(255, 255, 255));
        memory_save.setText("MS");
        memory_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        memory_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memory_saveActionPerformed(evt);
            }
        });
        jPanel2.add(memory_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 50, 30));

        memory_read.setBackground(new java.awt.Color(0, 0, 204));
        memory_read.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        memory_read.setForeground(new java.awt.Color(255, 255, 255));
        memory_read.setText("MR");
        memory_read.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        memory_read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memory_readActionPerformed(evt);
            }
        });
        jPanel2.add(memory_read, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 50, 30));

        memory_Clear.setBackground(new java.awt.Color(0, 0, 204));
        memory_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        memory_Clear.setForeground(new java.awt.Color(255, 255, 255));
        memory_Clear.setText("MC");
        memory_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        memory_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memory_ClearActionPerformed(evt);
            }
        });
        jPanel2.add(memory_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 50, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 420, 0));

        mem_dis.setBackground(new java.awt.Color(0, 0, 204));
        mem_dis.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mem_dis.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(mem_dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 230, 40));

        cos.setBackground(new java.awt.Color(0, 0, 204));
        cos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cos.setForeground(new java.awt.Color(255, 255, 255));
        cos.setText("Cos");
        cos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });
        jPanel2.add(cos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 50, 30));

        tan_1.setBackground(new java.awt.Color(0, 0, 204));
        tan_1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tan_1.setForeground(new java.awt.Color(255, 255, 255));
        tan_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tan-.png"))); // NOI18N
        tan_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tan_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tan_1ActionPerformed(evt);
            }
        });
        jPanel2.add(tan_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 50, 30));

        sin_1.setBackground(new java.awt.Color(0, 0, 204));
        sin_1.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        sin_1.setForeground(new java.awt.Color(255, 255, 255));
        sin_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sin-.png"))); // NOI18N
        sin_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sin_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sin_1ActionPerformed(evt);
            }
        });
        jPanel2.add(sin_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 50, 30));

        cos_1.setBackground(new java.awt.Color(0, 0, 204));
        cos_1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cos_1.setForeground(new java.awt.Color(255, 255, 255));
        cos_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cos-.png"))); // NOI18N
        cos_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cos_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cos_1ActionPerformed(evt);
            }
        });
        jPanel2.add(cos_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 50, 30));

        sin.setBackground(new java.awt.Color(0, 0, 204));
        sin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        sin.setForeground(new java.awt.Color(255, 255, 255));
        sin.setText("Sin");
        sin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });
        jPanel2.add(sin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 50, 30));

        tan.setBackground(new java.awt.Color(0, 0, 204));
        tan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tan.setForeground(new java.awt.Color(255, 255, 255));
        tan.setText("Tan");
        tan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });
        jPanel2.add(tan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 50, 30));

        cube.setBackground(new java.awt.Color(0, 0, 204));
        cube.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cube.setForeground(new java.awt.Color(255, 255, 255));
        cube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/x3.png"))); // NOI18N
        cube.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeActionPerformed(evt);
            }
        });
        jPanel2.add(cube, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 50, 30));

        squared.setBackground(new java.awt.Color(0, 0, 204));
        squared.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        squared.setForeground(new java.awt.Color(255, 255, 255));
        squared.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/x2.png"))); // NOI18N
        squared.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        squared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squaredActionPerformed(evt);
            }
        });
        jPanel2.add(squared, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 50, 30));

        btn_clear12.setBackground(new java.awt.Color(0, 0, 204));
        btn_clear12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_clear12.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1.png"))); // NOI18N
        btn_clear12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear12ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 50, 30));

        btn_clear13.setBackground(new java.awt.Color(0, 0, 204));
        btn_clear13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_clear13.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Square Root_32px_1.png"))); // NOI18N
        btn_clear13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear13ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 50, 30));

        pi.setBackground(new java.awt.Color(0, 0, 204));
        pi.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        pi.setForeground(new java.awt.Color(255, 255, 255));
        pi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Pi_25px_1.png"))); // NOI18N
        pi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piActionPerformed(evt);
            }
        });
        jPanel2.add(pi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 50, 30));

        btn_clear15.setBackground(new java.awt.Color(0, 0, 204));
        btn_clear15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_clear15.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Percentage_25px.png"))); // NOI18N
        btn_clear15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear15ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 50, 30));

        oct.setBackground(new java.awt.Color(0, 0, 204));
        oct.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        oct.setForeground(new java.awt.Color(255, 255, 255));
        oct.setText("Oct");
        oct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octActionPerformed(evt);
            }
        });
        jPanel2.add(oct, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 50, 30));

        hex.setBackground(new java.awt.Color(0, 0, 204));
        hex.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        hex.setForeground(new java.awt.Color(255, 255, 255));
        hex.setText("Hex");
        hex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexActionPerformed(evt);
            }
        });
        jPanel2.add(hex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 50, 30));

        exp.setBackground(new java.awt.Color(0, 0, 204));
        exp.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        exp.setForeground(new java.awt.Color(255, 255, 255));
        exp.setText("Exp");
        exp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expActionPerformed(evt);
            }
        });
        jPanel2.add(exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 50, 30));

        cube_root.setBackground(new java.awt.Color(0, 0, 204));
        cube_root.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        cube_root.setForeground(new java.awt.Color(255, 255, 255));
        cube_root.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cube.png"))); // NOI18N
        cube_root.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cube_root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cube_rootActionPerformed(evt);
            }
        });
        jPanel2.add(cube_root, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 50, 30));

        log.setBackground(new java.awt.Color(0, 0, 204));
        log.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        log.setForeground(new java.awt.Color(255, 255, 255));
        log.setText("Log");
        log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        jPanel2.add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 50, 30));

        sq_root.setBackground(new java.awt.Color(0, 0, 204));
        sq_root.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        sq_root.setForeground(new java.awt.Color(255, 255, 255));
        sq_root.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sq.png"))); // NOI18N
        sq_root.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sq_root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sq_rootActionPerformed(evt);
            }
        });
        jPanel2.add(sq_root, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 50, 30));

        bin.setBackground(new java.awt.Color(0, 0, 204));
        bin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        bin.setForeground(new java.awt.Color(255, 255, 255));
        bin.setText("Bin");
        bin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binActionPerformed(evt);
            }
        });
        jPanel2.add(bin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 50, 30));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 420, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Degree", "Grad", "Radiant" }));
        jPanel2.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 470, 550));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 360, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logoNew.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 80));

        jButton1.setBackground(new java.awt.Color(175, 165, 165));
        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back_25px_6.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 90, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("C A L C U L A T O R");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 70)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("SCIENTIFIC");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calculator.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        setSize(new java.awt.Dimension(865, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if(! zerodisp && !dcidisp){

            displayBox.setText(null);

        }
        displayBox.setText(displayBox.getText() + "7");
        zerodisp=true;
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if(! zerodisp && !dcidisp){

            displayBox.setText(null);

        }
        displayBox.setText(displayBox.getText() + "4");
        zerodisp=true;
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnplus_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplus_minusActionPerformed
        // TODO add your handling code here:
        inb=Double.parseDouble(String.valueOf(displayBox.getText()));
        out =inb *-1;
        if(out > -100000000 && out < 100000000){
            displayBox.setText(String.valueOf(out));
        }
        else{
            displayBox.setText("Error");

        }
        dcidisp=true;
        out =0;
    }//GEN-LAST:event_btnplus_minusActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        if(! zerodisp && !dcidisp){

            displayBox.setText(null);

        }
        displayBox.setText(displayBox.getText() + "0");

    }//GEN-LAST:event_btn0ActionPerformed

    private void btn0KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn0KeyPressed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_btn0KeyPressed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if(! zerodisp && !dcidisp){

            displayBox.setText(null);

        }
        displayBox.setText(displayBox.getText() + "2");
        zerodisp=true;
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if(! zerodisp && !dcidisp){

            displayBox.setText(null);

        }
        displayBox.setText(displayBox.getText() + "5");
        zerodisp=true;
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if(! zerodisp && !dcidisp){

            displayBox.setText(null);

        }
        displayBox.setText(displayBox.getText() + "8");
        zerodisp=true;
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multActionPerformed
        // TODO add your handling code here:

          if(op==0){
        
            ina =Double.parseDouble(String.valueOf(displayBox.getText()));
        }
        else{
        
         inb =Double.parseDouble(String.valueOf(displayBox.getText()));
        }
        if(op==1){
        ina =ina+inb;
        
        }
        
         if(op==2){
        ina =ina-inb;
        
        }
         
          if(op==3){
        ina =ina*inb;
        
        }
          
           if(op==4){
        ina =ina/inb;
        
        }
           
            if(op==5){
        ina =ina%inb /100;
        
        }
            
            displayBox.setText("0");
            dis.setText(String.valueOf(ina) + " x");
            op =3;
            zerodisp =false;
            dcidisp=false;
    }//GEN-LAST:event_btn_multActionPerformed

    private void btn_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minusActionPerformed
         // TODO add your handling code here:

          if(op==0){
        
            ina =Double.parseDouble(String.valueOf(displayBox.getText()));
        }
        else{
        
         inb =Double.parseDouble(String.valueOf(displayBox.getText()));
        }
        if(op==1){
        ina =ina+inb;
        
        }
        
         if(op==2){
        ina =ina-inb;
        
        }
         
          if(op==3){
        ina =ina*inb;
        
        }
          
           if(op==4){
        ina =ina/inb;
        
        }
           
            if(op==5){
        ina =ina%inb /100;
        
        }
            
            displayBox.setText("0");
            dis.setText(String.valueOf(ina) + "-");
            op =2;
            zerodisp =false;
            dcidisp=false;
    }//GEN-LAST:event_btn_minusActionPerformed

    private void btnequaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequaltActionPerformed
        // TODO add your handling code here:
        
        inb =Double.parseDouble(String.valueOf(displayBox.getText()));
        
        if(op ==0){
        
           out =inb;
            dis.setText(String.valueOf(inb));

        }
        if(op ==1){
        
            out =ina+inb;
            dis.setText(dis.getText()+String.valueOf(inb));

        }
        if(op ==2){
        
            out =ina-inb;
            dis.setText(dis.getText()+String.valueOf(inb));

        }
        
        if(op ==3){
        
            out =ina*inb;
            dis.setText(dis.getText()+String.valueOf(inb));

        }
        if(op ==4){
        
            out =ina/inb;
            dis.setText(dis.getText()+String.valueOf(inb));

        }
        if(op ==5){
        
            out =ina%inb /100;
            dis.setText(dis.getText()+String.valueOf(inb) + ")");

        }
        if(out > -100000000 && out < 100000000){
            displayBox.setText(String.valueOf(out));
        }
        else{
            displayBox.setText("Error");

        }
        
        ina =0;
        inb =0;
        out=0;
        
        op=0;
        zerodisp=false;
        dcidisp=false;
        

    }//GEN-LAST:event_btnequaltActionPerformed

    private void btn_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plusActionPerformed
        // TODO add your handling code here:
        if(op==0){
        
            ina =Double.parseDouble(String.valueOf(displayBox.getText()));
        }
        else{
        
         inb =Double.parseDouble(String.valueOf(displayBox.getText()));
        }
        if(op==1){
        ina =ina+inb;
        
        }
        
         if(op==2){
        ina =ina-inb;
        
        }
         
          if(op==3){
        ina =ina*inb;
        
        }
          
           if(op==4){
        ina =ina/inb;
        
        }
           
            if(op==5){
        ina =ina%inb /100;
        
        }
            
            displayBox.setText("0");
            dis.setText(String.valueOf(ina) + "+");
            op =1;
            zerodisp =false;
            dcidisp=false;

    }//GEN-LAST:event_btn_plusActionPerformed

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotActionPerformed
        // TODO add your handling code here:
        if(!dcidisp){
            displayBox.setText(displayBox.getText() +".");
            dcidisp=true;

        }
    }//GEN-LAST:event_btndotActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if(! zerodisp && !dcidisp){

            displayBox.setText(null);

        }
        displayBox.setText(displayBox.getText() + "3");
        zerodisp=true;
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if(! zerodisp && !dcidisp){

            displayBox.setText(null);

        }
        displayBox.setText(displayBox.getText() + "6");
        zerodisp=true;
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if(! zerodisp && !dcidisp){

            displayBox.setText(null);

        }
        displayBox.setText(displayBox.getText() + "9");
        zerodisp=true;
    }//GEN-LAST:event_btn9ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        dis.setText(null);
        displayBox.setText("0");
        zerodisp=false;
        dcidisp=false;
        ina =0;
        inb =0;
        out=0;

    }//GEN-LAST:event_resetActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        displayBox.setText("0");
        zerodisp=false;
        dcidisp=false;
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:

        String bsp=null;

        if(displayBox.getText().length()>0){
            StringBuilder strB = new StringBuilder(displayBox.getText());
            strB.deleteCharAt(displayBox.getText().length()-1);
            bsp=strB.toString();
            displayBox.setText(bsp);
        }
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        // TODO add your handling code here:

          if(op==0){
        
            ina =Double.parseDouble(String.valueOf(displayBox.getText()));
        }
        else{
        
         inb =Double.parseDouble(String.valueOf(displayBox.getText()));
        }
        if(op==1){
        ina =ina+inb;
        
        }
        
         if(op==2){
        ina =ina-inb;
        
        }
         
          if(op==3){
        ina =ina*inb;
        
        }
          
           if(op==4){
        ina =ina/inb;
        
        }
           
            if(op==5){
        ina =ina%inb /100;
        
        }
            
            displayBox.setText("0");
            dis.setText(String.valueOf(ina) + "÷");
            op =4;
            zerodisp =false;
            dcidisp=false;
    }//GEN-LAST:event_btn_divActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if(! zerodisp && !dcidisp){

            displayBox.setText(null);

        }
        displayBox.setText(displayBox.getText() + "1");
        zerodisp=true;
    }//GEN-LAST:event_btn1ActionPerformed

    private void displayBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayBoxKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_displayBoxKeyPressed

    private void displayBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayBoxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_displayBoxKeyReleased

    private void displayBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayBoxKeyTyped
        // TODO add your handling code here:
    
    }//GEN-LAST:event_displayBoxKeyTyped

    private void memory_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memory_saveActionPerformed
        // TODO add your handling code here:
        mem_dis.setText(String.valueOf(displayBox.getText()));
    }//GEN-LAST:event_memory_saveActionPerformed

    private void memory_readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memory_readActionPerformed
        // TODO add your handling code here:
        displayBox.setText(String.valueOf((mem_dis.getText())));

    }//GEN-LAST:event_memory_readActionPerformed

    private void memory_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memory_ClearActionPerformed
        // TODO add your handling code here:
        mem_dis.setText("0");
    }//GEN-LAST:event_memory_ClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        main_form1 mf = new main_form1();
        mf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        // TODO add your handling code here:
     inb = Double.parseDouble(String.valueOf(displayBox.getText()));
      
      if(combo.getSelectedItem().equals("Degree")){
           dis.setText("cos(" + String.valueOf(inb) + ")");
            inb =inb*0.01745240643728351281941897851632;
        out=Math.cos(inb);
      displayBox.setText(String.valueOf(out));
      out =0;
      }
      
      else if(combo.getSelectedItem().equals("Radiant")){
         dis.setText("cos(" + String.valueOf(inb) + ")");
         
        out=Math.cos(inb);
      displayBox.setText(String.valueOf(out));
      out =0;
      }
   
    }//GEN-LAST:event_cosActionPerformed

    private void tan_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tan_1ActionPerformed
        // TODO add your handling code here:
         inb = Double.parseDouble(String.valueOf(displayBox.getText()));
        if(!degree){
            dis.setText("tanh(" + String.valueOf(inb) + ")");
            
            inb =inb*0.174532925;
        }
        out=Math.tanh(inb);
        displayBox.setText(String.valueOf(out));
        out=0;
    }//GEN-LAST:event_tan_1ActionPerformed

       
   
     
    
    private void sin_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sin_1ActionPerformed
        // TODO add your handling code here:
        inb = Double.parseDouble(String.valueOf(displayBox.getText()));
   
      if(combo.getSelectedItem().equals("Degree")){
           dis.setText("sin(" + String.valueOf(inb) + ")");
         
          
         out=Math.sinh(inb);
      displayBox.setText(String.valueOf(out));
      out =0;
      }
      
      else if(combo.getSelectedItem().equals("Radiant")){
           dis.setText("sin(" + String.valueOf(inb) + ")");
        
          
        out=Math.toRadians(Math.sinh(inb));
      displayBox.setText(String.valueOf(out));
      out =0;
      }
    }//GEN-LAST:event_sin_1ActionPerformed

    private void cos_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cos_1ActionPerformed
        // TODO add your handling code here:
             inb = Double.parseDouble(String.valueOf(displayBox.getText()));
        if(!degree){
            dis.setText("cosh(" + String.valueOf(inb) + ")");
            
            inb =inb*0.01745240643;
        }
        out=Math.cosh(inb);
        displayBox.setText(String.valueOf(out));
        out=0;
    }//GEN-LAST:event_cos_1ActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        // TODO add your handling code here:
  
       inb = Double.parseDouble(String.valueOf(displayBox.getText()));
      
      if(combo.getSelectedItem().equals("Degree")){
           dis.setText("sin(" + String.valueOf(inb) + ")");
            inb =inb*0.01745240643728351281941897851632;
        out=Math.sin(inb);
      displayBox.setText(String.valueOf(out));
      out =0;
      }
      
      else if(combo.getSelectedItem().equals("Radiant")){
         dis.setText("sin(" + String.valueOf(inb) + ")");
         
        out=Math.sin(inb);
      displayBox.setText(String.valueOf(out));
      out =0;
      }
      
    }//GEN-LAST:event_sinActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        // TODO add your handling code here:
        inb = Double.parseDouble(String.valueOf(displayBox.getText()));
      
      if(combo.getSelectedItem().equals("Degree")){
           dis.setText("cos(" + String.valueOf(inb) + ")");
          inb =inb*0.01745240643;
          
          out=Math.tan(inb);
      displayBox.setText(String.valueOf(out));
      out =0;
      }
      
      else if(combo.getSelectedItem().equals("Radiant")){
           dis.setText("cos(" + String.valueOf(inb) + ")");
        
          
          out=Math.tan(inb);
      displayBox.setText(String.valueOf(out));
      out =0;
      }
    }//GEN-LAST:event_tanActionPerformed

    private void cubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeActionPerformed
        inb =Double.parseDouble(String.valueOf(displayBox.getText()));
        out =inb*inb*inb;
        if(out > -100000000 && out < 100000000){
            displayBox.setText(String.valueOf(out));
        }
        else{
            displayBox.setText("Error");

        }
        dis.setText(String.valueOf(inb) +"³");
        out=0;
        
    }//GEN-LAST:event_cubeActionPerformed

    private void squaredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squaredActionPerformed
        // TODO add your handling code here:
        inb =Double.parseDouble(String.valueOf(displayBox.getText()));
        out =inb*inb;
        if(out > -100000000 && out < 100000000){
            displayBox.setText(String.valueOf(out));
        }
        else{
            displayBox.setText("Error");

        }
        dis.setText(String.valueOf(inb) +"²");
        out=0;
        
        
    }//GEN-LAST:event_squaredActionPerformed

    private void btn_clear12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear12ActionPerformed
        // TODO add your handling code here:
        inb =Double.parseDouble(String.valueOf(displayBox.getText()));
        out=1/inb;
        if(out > -100000000 && out < 100000000){
            displayBox.setText(String.valueOf(out));
        }
        else{
            displayBox.setText("Error");

        }
        
        dis.setText("1/" +String.valueOf((inb)));
        out=0;
    }//GEN-LAST:event_btn_clear12ActionPerformed

    private void btn_clear13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clear13ActionPerformed

    private void piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piActionPerformed
        // TODO add your handling code here:
        displayBox.setText(String.valueOf(Math.PI));
    }//GEN-LAST:event_piActionPerformed

    private void btn_clear15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear15ActionPerformed
        // TODO add your handling code here:
        
        ina =Double.parseDouble(String.valueOf(displayBox.getText()));
        displayBox.setText("0");
        dis.setText(String.valueOf(ina) + " % (" );
        
            zerodisp =false;
            dcidisp=false;
             op = 5;
    }//GEN-LAST:event_btn_clear15ActionPerformed

    private void octActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octActionPerformed

    private void hexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hexActionPerformed

    private void expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expActionPerformed

    private void cube_rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cube_rootActionPerformed
        inb =Double.parseDouble(String.valueOf(displayBox.getText()));
        out =Math.cbrt(inb);

            displayBox.setText(String.valueOf(out));

        dis.setText("³√" + String.valueOf(inb));
        out=0;
        
          
    }//GEN-LAST:event_cube_rootActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
       inb =Double.parseDouble(String.valueOf(displayBox.getText()));
       out=Math.log(inb);
       displayBox.setText(String.valueOf(out));
       
       dis.setText("Log("+ String.valueOf(inb)+")");
       out=0;
    }//GEN-LAST:event_logActionPerformed

    private void sq_rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sq_rootActionPerformed
        // TODO add your handling code here:
         inb =Double.parseDouble(String.valueOf(displayBox.getText()));
        out =Math.sqrt(inb);

            displayBox.setText(String.valueOf(out));

        dis.setText("√" + String.valueOf(inb));
        out=0;
    }//GEN-LAST:event_sq_rootActionPerformed

    private void binActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_binActionPerformed

    private void displayBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scientific_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scientific_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scientific_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scientific_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scientific_calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bin;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_clear12;
    private javax.swing.JButton btn_clear13;
    private javax.swing.JButton btn_clear15;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_minus;
    private javax.swing.JButton btn_mult;
    private javax.swing.JButton btn_plus;
    private javax.swing.JButton btndot;
    private javax.swing.JButton btnequalt;
    private javax.swing.JButton btnplus_minus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton cos;
    private javax.swing.JButton cos_1;
    private javax.swing.JButton cube;
    private javax.swing.JButton cube_root;
    private javax.swing.JTextField dis;
    private javax.swing.JTextField displayBox;
    private javax.swing.JButton exp;
    private javax.swing.JButton hex;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton log;
    private javax.swing.JTextField mem_dis;
    private javax.swing.JButton memory_Clear;
    private javax.swing.JButton memory_read;
    private javax.swing.JButton memory_save;
    private javax.swing.JButton oct;
    private javax.swing.JButton pi;
    private javax.swing.JButton reset;
    private javax.swing.JButton sin;
    private javax.swing.JButton sin_1;
    private javax.swing.JButton sq_root;
    private javax.swing.JButton squared;
    private javax.swing.JButton tan;
    private javax.swing.JButton tan_1;
    // End of variables declaration//GEN-END:variables
}
