/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPack;


import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author oSikaNi iSraeL
 */
public class temperatrure_Conversion extends javax.swing.JFrame {

    /**
     * Creates new form temperatrure_Conversion
     */
    public temperatrure_Conversion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cov_Box = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        amt_Box = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("To");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("From");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -70, 300, 630));

        cov_Box.setEditable(false);
        cov_Box.setBackground(new java.awt.Color(0, 0, 153));
        cov_Box.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cov_Box.setForeground(new java.awt.Color(255, 255, 255));
        cov_Box.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        cov_Box.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Result", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        cov_Box.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jPanel2.add(cov_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 170, 60));

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Temperature_20px_2.png"))); // NOI18N
        jButton2.setText("CONVERT");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Restart_20px_3.png"))); // NOI18N
        jButton3.setText("RESET");
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(0, 0, 204));
        jComboBox2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Celsius", "Fahrenheit ", "Kelvin" }));
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 30));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 204));
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Celsius", "Fahrenheit ", "Kelvin" }));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 30));

        amt_Box.setBackground(new java.awt.Color(0, 0, 153));
        amt_Box.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        amt_Box.setForeground(new java.awt.Color(255, 255, 255));
        amt_Box.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Enter Value", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        amt_Box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amt_BoxKeyPressed(evt);
            }
        });
        jPanel2.add(amt_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 170, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 350, 550));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logoNew.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 45)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("TEMPERATURE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 100));

        jButton1.setBackground(new java.awt.Color(175, 165, 165));
        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back_25px_6.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 90, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 330, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("C O N V E R S I O N");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 50));

        jLabel2.setBackground(new java.awt.Color(148, 34, 25));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tempr.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 153));
        jMenuBar1.setBorder(null);
        jMenuBar1.setToolTipText("Menu");
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setOpaque(false);
        jMenuBar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseDragged(evt);
            }
        });
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuBar1MousePressed(evt);
            }
        });

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Menu_15px_1.png"))); // NOI18N
        jMenu2.setText("File");

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_15px.png"))); // NOI18N
        jMenuItem11.setText("Close");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/About_15px_2.png"))); // NOI18N
        jMenuItem14.setText("About");
        jMenu2.add(jMenuItem14);

        jMenuBar1.add(jMenu2);

        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Menu");
        jMenu1.setToolTipText("Menu");
        jMenu1.setContentAreaFilled(false);
        jMenu1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Weight_20px_1.png"))); // NOI18N
        jMenuItem1.setText("Mass");
        jMenuItem1.setBorderPainted(false);
        jMenuItem1.setContentAreaFilled(false);
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setBackground(new java.awt.Color(0, 0, 153));
        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Storage_20px_1.png"))); // NOI18N
        jMenuItem2.setText("Digital Storage");
        jMenuItem2.setContentAreaFilled(false);
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Time_20px_1.png"))); // NOI18N
        jMenuItem3.setText("Time");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Length_20px_1.png"))); // NOI18N
        jMenuItem4.setText("Length");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Energy Meter_20px_1.png"))); // NOI18N
        jMenuItem5.setText("Energy");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Speed_20px_1.png"))); // NOI18N
        jMenuItem6.setText("Speed");
        jMenuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Gas Station_20px_1.png"))); // NOI18N
        jMenuItem7.setText("Fuel Economy");
        jMenuItem7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Temperature_20px_1.png"))); // NOI18N
        jMenuItem8.setText("Temperature");
        jMenuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Pressure_20px_1.png"))); // NOI18N
        jMenuItem9.setText("Pressure");
        jMenuItem9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Trigonometry_20px_1.png"))); // NOI18N
        jMenuItem10.setText("Plane Angle");
        jMenuItem10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Volume_20px_1.png"))); // NOI18N
        jMenuItem12.setText("Volume");
        jMenuItem12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Area Chart_20px_1.png"))); // NOI18N
        jMenuItem13.setText("Area");
        jMenuItem13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(701, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        main_form1 mf = new main_form1();
        mf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(
                jComboBox1.getSelectedItem().equals("Choose one...")
                ||jComboBox1.getSelectedItem().equals("Choose one...")
                || amt_Box.getText().isEmpty())
            
        {
            setVisible(false);
            temperature_Conv_error tc = new temperature_Conv_error();
            tc.setVisible(true);        
        }
        
        else{
            
            try {
            if(jComboBox1.getSelectedItem().equals("Celsius")&&jComboBox2.getSelectedItem().equals("Celsius")){

                double value = Double.parseDouble(amt_Box.getText());

                double res = value *1;

                cov_Box.setText(Double.toString(res)+ "°C");

            }
            else if (jComboBox1.getSelectedItem().equals("Celsius") && jComboBox2.getSelectedItem().equals("Fahrenheit ")){

                double input = Double.parseDouble(amt_Box.getText());

                double result = input*1.8+32;

                cov_Box.setText(Double.toString(result)+ "°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Celsius") && jComboBox2.getSelectedItem().equals("Kelvin")){
                double y_input = Double.parseDouble(amt_Box.getText());

                double y_result = y_input+273.15;

                cov_Box.setText(Double.toString(y_result)+"K");

            }

            //Fahrenheit conversions

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ") && jComboBox2.getSelectedItem().equals("Celsius")){

                double val =Double.parseDouble(amt_Box.getText());

                double re =(val-32)*5/9;

                cov_Box.setText(Double.toString(re)+"°C");

            }

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ") && jComboBox2.getSelectedItem().equals("Fahrenheit ")){

                double amt = Double.parseDouble(amt_Box.getText());

                double ans = amt *1;

                cov_Box.setText(Double.toString(ans)+"°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ")&& jComboBox2.getSelectedItem().equals("Kelvin")){

                double amt_2 =Double.parseDouble(amt_Box.getText());

                double ans1=(amt_2+459.67)*5/9;

                cov_Box.setText(Double.toString(ans1)+"K");

            }

            //kelvin conversion

            else if (jComboBox1.getSelectedItem().equals("Kelvin")&&jComboBox2.getSelectedItem().equals("Celsius")){

                double amtt= Double.parseDouble(amt_Box.getText());

                double ans =amtt-273.15;

                cov_Box.setText(Double.toString(ans)+ "°C");
            }

            else if (jComboBox1.getSelectedItem().equals("Kelvin") && jComboBox2.getSelectedItem().equals("Fahrenheit "))

            {
                double amt_t = Double.parseDouble(amt_Box.getText());

                double ans3 = amt_t *9/5-459.67;

                cov_Box.setText(Double.toString(ans3)+"°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Kelvin") && jComboBox2.getSelectedItem().equals("Kelvin")){

                double y_amt = Double.parseDouble(amt_Box.getText());

                double result_1 = y_amt*1;

                cov_Box.setText(Double.toString(result_1)+"K");

            }

        }catch (Exception e){
            
           setVisible(false);
           temperature_Exception tp = new temperature_Exception();
           tp.setVisible(true);

        }
        
        }

        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        jComboBox1.setSelectedItem("Choose one...");
        jComboBox2.setSelectedItem("Choose one...");
        amt_Box.setText(null);
        cov_Box.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        mass_Conversion mc = new mass_Conversion();
        mc.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        digital_Storage mc = new digital_Storage();
        mc.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        time_Conversion mc = new time_Conversion();
        mc.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        lenght_Conversion mc = new lenght_Conversion();
        mc.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        setVisible(false);
        energy_Conversion ec = new energy_Conversion();
        ec.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        setVisible(false);
        speed_conversion mc = new speed_conversion();
        mc.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        fuel_Economy fe = new fuel_Economy();
        fe.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        temperatrure_Conversion mc = new temperatrure_Conversion();
        mc.setVisible(true);

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        pressure_Conversion mc = new pressure_Conversion();
        mc.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        plane_Angle mc = new plane_Angle();
        mc.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        volume_Conversion mc = new volume_Conversion();
        mc.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        Unit_Conversion uc = new Unit_Conversion();
        uc.setVisible(true);

    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuBar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuBar1MouseDragged

    private void jMenuBar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuBar1MousePressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             if(
                jComboBox1.getSelectedItem().equals("Choose one...")
                ||jComboBox1.getSelectedItem().equals("Choose one...")
                || amt_Box.getText().isEmpty())
            
        {
            setVisible(false);
            temperature_Conv_error tc = new temperature_Conv_error();
            tc.setVisible(true);        
        }
        
        else{
            
            try {
            if(jComboBox1.getSelectedItem().equals("Celsius")&&jComboBox2.getSelectedItem().equals("Celsius")){

                double value = Double.parseDouble(amt_Box.getText());

                double res = value *1;

                cov_Box.setText(Double.toString(res)+ "°C");

            }
            else if (jComboBox1.getSelectedItem().equals("Celsius") && jComboBox2.getSelectedItem().equals("Fahrenheit ")){

                double input = Double.parseDouble(amt_Box.getText());

                double result = input*1.8+32;

                cov_Box.setText(Double.toString(result)+ "°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Celsius") && jComboBox2.getSelectedItem().equals("Kelvin")){
                double y_input = Double.parseDouble(amt_Box.getText());

                double y_result = y_input+273.15;

                cov_Box.setText(Double.toString(y_result)+"K");

            }

            //Fahrenheit conversions

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ") && jComboBox2.getSelectedItem().equals("Celsius")){

                double val =Double.parseDouble(amt_Box.getText());

                double re =(val-32)*5/9;

                cov_Box.setText(Double.toString(re)+"°C");

            }

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ") && jComboBox2.getSelectedItem().equals("Fahrenheit ")){

                double amt = Double.parseDouble(amt_Box.getText());

                double ans = amt *1;

                cov_Box.setText(Double.toString(ans)+"°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ")&& jComboBox2.getSelectedItem().equals("Kelvin")){

                double amt_2 =Double.parseDouble(amt_Box.getText());

                double ans1=(amt_2+459.67)*5/9;

                cov_Box.setText(Double.toString(ans1)+"K");

            }

            //kelvin conversion

            else if (jComboBox1.getSelectedItem().equals("Kelvin")&&jComboBox2.getSelectedItem().equals("Celsius")){

                double amtt= Double.parseDouble(amt_Box.getText());

                double ans =amtt-273.15;

                cov_Box.setText(Double.toString(ans)+ "°C");
            }

            else if (jComboBox1.getSelectedItem().equals("Kelvin") && jComboBox2.getSelectedItem().equals("Fahrenheit "))

            {
                double amt_t = Double.parseDouble(amt_Box.getText());

                double ans3 = amt_t *9/5-459.67;

                cov_Box.setText(Double.toString(ans3)+"°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Kelvin") && jComboBox2.getSelectedItem().equals("Kelvin")){

                double y_amt = Double.parseDouble(amt_Box.getText());

                double result_1 = y_amt*1;

                cov_Box.setText(Double.toString(result_1)+"K");

            }

        }catch (Exception e){
            
           setVisible(false);
           temperature_Exception tp = new temperature_Exception();
           tp.setVisible(true);

        }
        
        }
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void amt_BoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amt_BoxKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             if(
                jComboBox1.getSelectedItem().equals("Choose one...")
                ||jComboBox1.getSelectedItem().equals("Choose one...")
                || amt_Box.getText().isEmpty())
            
        {
            setVisible(false);
            temperature_Conv_error tc = new temperature_Conv_error();
            tc.setVisible(true);        
        }
        
        else{
            
            try {
            if(jComboBox1.getSelectedItem().equals("Celsius")&&jComboBox2.getSelectedItem().equals("Celsius")){

                double value = Double.parseDouble(amt_Box.getText());

                double res = value *1;

                cov_Box.setText(Double.toString(res)+ "°C");

            }
            else if (jComboBox1.getSelectedItem().equals("Celsius") && jComboBox2.getSelectedItem().equals("Fahrenheit ")){

                double input = Double.parseDouble(amt_Box.getText());

                double result = input*1.8+32;

                cov_Box.setText(Double.toString(result)+ "°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Celsius") && jComboBox2.getSelectedItem().equals("Kelvin")){
                double y_input = Double.parseDouble(amt_Box.getText());

                double y_result = y_input+273.15;

                cov_Box.setText(Double.toString(y_result)+"K");

            }

            //Fahrenheit conversions

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ") && jComboBox2.getSelectedItem().equals("Celsius")){

                double val =Double.parseDouble(amt_Box.getText());

                double re =(val-32)*5/9;

                cov_Box.setText(Double.toString(re)+"°C");

            }

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ") && jComboBox2.getSelectedItem().equals("Fahrenheit ")){

                double amt = Double.parseDouble(amt_Box.getText());

                double ans = amt *1;

                cov_Box.setText(Double.toString(ans)+"°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ")&& jComboBox2.getSelectedItem().equals("Kelvin")){

                double amt_2 =Double.parseDouble(amt_Box.getText());

                double ans1=(amt_2+459.67)*5/9;

                cov_Box.setText(Double.toString(ans1)+"K");

            }

            //kelvin conversion

            else if (jComboBox1.getSelectedItem().equals("Kelvin")&&jComboBox2.getSelectedItem().equals("Celsius")){

                double amtt= Double.parseDouble(amt_Box.getText());

                double ans =amtt-273.15;

                cov_Box.setText(Double.toString(ans)+ "°C");
            }

            else if (jComboBox1.getSelectedItem().equals("Kelvin") && jComboBox2.getSelectedItem().equals("Fahrenheit "))

            {
                double amt_t = Double.parseDouble(amt_Box.getText());

                double ans3 = amt_t *9/5-459.67;

                cov_Box.setText(Double.toString(ans3)+"°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Kelvin") && jComboBox2.getSelectedItem().equals("Kelvin")){

                double y_amt = Double.parseDouble(amt_Box.getText());

                double result_1 = y_amt*1;

                cov_Box.setText(Double.toString(result_1)+"K");

            }

        }catch (Exception e){
            
           setVisible(false);
           temperature_Exception tp = new temperature_Exception();
           tp.setVisible(true);

        }
        
        }
        }
    }//GEN-LAST:event_amt_BoxKeyPressed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:..
        
        
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             if(
                jComboBox1.getSelectedItem().equals("Choose one...")
                ||jComboBox1.getSelectedItem().equals("Choose one...")
                || amt_Box.getText().isEmpty())
            
        {
            setVisible(false);
            temperature_Conv_error tc = new temperature_Conv_error();
            tc.setVisible(true);        
        }
        
        else{
            
            try {
            if(jComboBox1.getSelectedItem().equals("Celsius")&&jComboBox2.getSelectedItem().equals("Celsius")){

                double value = Double.parseDouble(amt_Box.getText());

                double res = value *1;

                cov_Box.setText(Double.toString(res)+ "°C");

            }
            else if (jComboBox1.getSelectedItem().equals("Celsius") && jComboBox2.getSelectedItem().equals("Fahrenheit ")){

                double input = Double.parseDouble(amt_Box.getText());

                double result = input*1.8+32;

                cov_Box.setText(Double.toString(result)+ "°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Celsius") && jComboBox2.getSelectedItem().equals("Kelvin")){
                double y_input = Double.parseDouble(amt_Box.getText());

                double y_result = y_input+273.15;

                cov_Box.setText(Double.toString(y_result)+"K");

            }

            //Fahrenheit conversions

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ") && jComboBox2.getSelectedItem().equals("Celsius")){

                double val =Double.parseDouble(amt_Box.getText());

                double re =(val-32)*5/9;

                cov_Box.setText(Double.toString(re)+"°C");

            }

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ") && jComboBox2.getSelectedItem().equals("Fahrenheit ")){

                double amt = Double.parseDouble(amt_Box.getText());

                double ans = amt *1;

                cov_Box.setText(Double.toString(ans)+"°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ")&& jComboBox2.getSelectedItem().equals("Kelvin")){

                double amt_2 =Double.parseDouble(amt_Box.getText());

                double ans1=(amt_2+459.67)*5/9;

                cov_Box.setText(Double.toString(ans1)+"K");

            }

            //kelvin conversion

            else if (jComboBox1.getSelectedItem().equals("Kelvin")&&jComboBox2.getSelectedItem().equals("Celsius")){

                double amtt= Double.parseDouble(amt_Box.getText());

                double ans =amtt-273.15;

                cov_Box.setText(Double.toString(ans)+ "°C");
            }

            else if (jComboBox1.getSelectedItem().equals("Kelvin") && jComboBox2.getSelectedItem().equals("Fahrenheit "))

            {
                double amt_t = Double.parseDouble(amt_Box.getText());

                double ans3 = amt_t *9/5-459.67;

                cov_Box.setText(Double.toString(ans3)+"°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Kelvin") && jComboBox2.getSelectedItem().equals("Kelvin")){

                double y_amt = Double.parseDouble(amt_Box.getText());

                double result_1 = y_amt*1;

                cov_Box.setText(Double.toString(result_1)+"K");

            }

        }catch (Exception e){
            
           setVisible(false);
           temperature_Exception tp = new temperature_Exception();
           tp.setVisible(true);

        }
        
        }
        }
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed

        // TODO add your handling code here:
        
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             if(
                jComboBox1.getSelectedItem().equals("Choose one...")
                ||jComboBox1.getSelectedItem().equals("Choose one...")
                || amt_Box.getText().isEmpty())
            
        {
            setVisible(false);
            temperature_Conv_error tc = new temperature_Conv_error();
            tc.setVisible(true);        
        }
        
        else{
            
            try {
            if(jComboBox1.getSelectedItem().equals("Celsius")&&jComboBox2.getSelectedItem().equals("Celsius")){

                double value = Double.parseDouble(amt_Box.getText());

                double res = value *1;

                cov_Box.setText(Double.toString(res)+ "°C");

            }
            else if (jComboBox1.getSelectedItem().equals("Celsius") && jComboBox2.getSelectedItem().equals("Fahrenheit ")){

                double input = Double.parseDouble(amt_Box.getText());

                double result = input*1.8+32;

                cov_Box.setText(Double.toString(result)+ "°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Celsius") && jComboBox2.getSelectedItem().equals("Kelvin")){
                double y_input = Double.parseDouble(amt_Box.getText());

                double y_result = y_input+273.15;

                cov_Box.setText(Double.toString(y_result)+"K");

            }

            //Fahrenheit conversions

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ") && jComboBox2.getSelectedItem().equals("Celsius")){

                double val =Double.parseDouble(amt_Box.getText());

                double re =(val-32)*5/9;

                cov_Box.setText(Double.toString(re)+"°C");

            }

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ") && jComboBox2.getSelectedItem().equals("Fahrenheit ")){

                double amt = Double.parseDouble(amt_Box.getText());

                double ans = amt *1;

                cov_Box.setText(Double.toString(ans)+"°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Fahrenheit ")&& jComboBox2.getSelectedItem().equals("Kelvin")){

                double amt_2 =Double.parseDouble(amt_Box.getText());

                double ans1=(amt_2+459.67)*5/9;

                cov_Box.setText(Double.toString(ans1)+"K");

            }

            //kelvin conversion

            else if (jComboBox1.getSelectedItem().equals("Kelvin")&&jComboBox2.getSelectedItem().equals("Celsius")){

                double amtt= Double.parseDouble(amt_Box.getText());

                double ans =amtt-273.15;

                cov_Box.setText(Double.toString(ans)+ "°C");
            }

            else if (jComboBox1.getSelectedItem().equals("Kelvin") && jComboBox2.getSelectedItem().equals("Fahrenheit "))

            {
                double amt_t = Double.parseDouble(amt_Box.getText());

                double ans3 = amt_t *9/5-459.67;

                cov_Box.setText(Double.toString(ans3)+"°F");
            }

            else if (jComboBox1.getSelectedItem().equals("Kelvin") && jComboBox2.getSelectedItem().equals("Kelvin")){

                double y_amt = Double.parseDouble(amt_Box.getText());

                double result_1 = y_amt*1;

                cov_Box.setText(Double.toString(result_1)+"K");

            }

        }catch (Exception e){
            
           setVisible(false);
           temperature_Exception tp = new temperature_Exception();
           tp.setVisible(true);

        }
        
        }
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
              jComboBox1.setSelectedItem("Choose one...");
        jComboBox2.setSelectedItem("Choose one...");
        amt_Box.setText(null);
        cov_Box.setText(null);
        }
    }//GEN-LAST:event_jButton3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(temperatrure_Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(temperatrure_Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(temperatrure_Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(temperatrure_Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new temperatrure_Conversion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt_Box;
    private javax.swing.JTextField cov_Box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
